[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main.py"
