[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
    "cd scrapers",
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd scrapers && celery -A celery_app worker --loglevel=info --concurrency=5"
