[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && playwright install chromium"

[deploy]
startCommand = "celery -A celery_app worker --loglevel=info --concurrency=5"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
PLAYWRIGHT_BROWSERS_PATH = "/tmp/playwright-browsers"
HEADLESS = "true"
